module.exports = {
    // Defaults
    DEFAULT_CULTURE_CODE: 'A000',
    DEFAULT_QUESTION_SET_CODE: 'A000',
    DEFAULT_TEACHER_ID: 1,
    DEFAULT_QUESTION_SET_CULTURE_ID: 1,
    DEFAULT_CLASSROOM_ID: 1,

    // Sessions
    INITIAL_SESSION: 1,
    PRACTICE_SESSION: -1,

    // Weeks
    MIN_WEEKS: 1
};